feat OT-170-32-: endpoint delete user
alkemyTech/OT170-Ruby-server pull request #11
Opened 2022-03-27 22:50 UTC by DevChristians

COMO usuario
QUIERO eliminar mi usuario
PARA darme de baja del sistema

Criterios de aceptación:
DELETE a /user/:id Deberá reicibir el id del usuario con el método DELETE. El borrado debe ser lógico.

2022-03-28 03:20 UTC, FernandoCiballero commented on config/routes.rb
> +      delete '/users/:id', to: 'users#destroy'
I recommend to use the `resources` method to simplify this.
```suggestion
      resources :users, only: :destroy
```

2022-03-28 03:23 UTC, FernandoCiballero commented on app/controllers/api/v1/users_controller.rb
> +        render json: 'User deleted', status: :ok
The `head :no_content` is more commonly used in these cases.

2022-03-28 03:25 UTC, FernandoCiballero requested changes
Great job Christians!!! 👏 left some comments.

2022-03-29 13:45 UTC, DevChristians commented
hi guys, corrections are done

2022-04-03 22:31 UTC, FernandoCiballero approved these changes
Great job!!! 👏

2022-04-03 22:31 UTC, merged