feat/OT170-33-middleware-de-ownership
alkemyTech/OT170-Ruby-server pull request #19
Opened 2022-03-31 22:32 UTC by givaleria

COMO usuario
QUIERO acceder únicamente a las secciones permitidas para mi rol
PARA completar ciertas acciones

Criterios de aceptación:
Se utilizará para proteger endpoints que son solo para el usuario actual. Deberá verificar el parámetro id y compararlo con el ID del usuario enviado en el token JWT, caso contrario, devolver error 403. Sin embargo, si el usuario que es enviado en el token es administrador, si le permitirá continuar

2022-04-04 00:58 UTC, FernandoCiballero commented on Gemfile
> +gem 'rack', '~> 2.2', '>= 2.2.3' # https://rubygems.org/gems/rack
I'm not sure in this case, but `rack` is a dependency of `rails`(maybe don't need to include it in Gemfile).

2022-04-04 01:01 UTC, FernandoCiballero requested changes
Great Job Gisela!!! 👏  I left a comment.
Would be great to make a demo for this feature to show it to the team.

2022-04-20 23:13 UTC, DevChristians approved these changes

2022-04-20 23:13 UTC, DevChristians commented
@fabiianZ  dale el approve a gise para que podamos hacer merge

2022-04-21 16:26 UTC, fabiianZ approved these changes

2022-04-22 22:45 UTC, FerkoxGG approved these changes

2024-06-26 15:47 UTC, closed without merging