fear-0T170-17-create-model-migration-and-controller-user
alkemyTech/OT170-Ruby-server pull request #3
Opened 2022-03-18 16:21 UTC by pabloayalaalvarez

Summary:

-Create model of user
-Create db and migration of user 
-Create AddDiscardedAtToUser

2022-03-19 00:01 UTC, FernandoCiballero commented on Gemfile
> +gem 'discard', '~> 1.2'
Please put the gem in alphabetical order like the other ones.

2022-03-19 00:04 UTC, FernandoCiballero requested changes
Great job Pablo!!! 👏  . Please create a tag like `work in progress` if your PR is not yet finished.

2022-03-19 17:02 UTC, DevChristians commented on config/routes.rb
> +  resources :users
I think the routes still don't go yet

2022-03-20 16:08 UTC, FernandoCiballero requested changes
Be careful not to delete folders and files. The ticket asks you to create an empty controller file.

2022-03-22 02:11 UTC, FernandoCiballero commented on config/environments/production.rb
> +
Please check this config because it is duplicated in the file and is not required in the ticket.

2022-03-22 02:13 UTC, FernandoCiballero commented on Gemfile
> +gem "image_processing", ">= 1.2"
This gem is not a requirement of the ticket, please check [this tutorial](https://codigofacilito.com/articulos/active-storage) about how to configure active storage in the project.

2022-03-22 02:15 UTC, FernandoCiballero requested changes
Please check the ticket's requirements because you are missing to create or upload some files.

2022-03-24 01:17 UTC, DevChristians requested changes

2022-03-24 13:22 UTC, Ezequiel-Padilla commented on spec/factories/users.rb
> +  end
use faker

2022-03-24 13:23 UTC, Ezequiel-Padilla commented on app/models/user.rb
> +  validates :email, presence: true
add an empty line between active storage and validates

2022-03-26 16:43 UTC, FernandoCiballero approved these changes
Great Job Pablo!!! 👍 I've some missing files, so you have to read carefully every ticket's requirement.

2022-03-26 16:45 UTC, merged