feat-OT170-85: add pagination members
alkemyTech/OT170-Ruby-server pull request #49
Opened 2022-04-20 02:47 UTC by DevChristians

COMO usuario
QUIERO visualizar los resultados de Miembros paginados
PARA aumentar la velocidad de respuesta

Criterios de aceptación:
Cuando se realice la petición para listar, los resultados deberán paginarse de a 10. En la respuesta, se deberán mostrar los resultados y las urls para la página anterior y siguiente (si corresponden). La página actual se obtendrá del parámetro de query ?page

2022-04-20 03:08 UTC, FernandoCiballero commented on app/controllers/api/v1/members_controller.rb
> +        render json: MemberSerializer.new(@member, { fields: { member: [:name] } }).serializable_hash
what is the purpose of this `{ fields: { member: [:name] } }`, maybe you don't need it

2022-04-20 03:11 UTC, FernandoCiballero commented on app/controllers/api/v1/members_controller.rb
> +        @pagy, @member = pagy(Member.all, items: params[:items] || 10, page: params[:page] || 1)
You can usar the file pagy.rb to leave the items fixed to 10.
```suggestion
        @pagy, @member = pagy(Member.all, page: params[:page] || 1)
```

2022-04-20 03:12 UTC, FernandoCiballero requested changes
Great Job!!! 👏  leave some comments.

2022-04-21 15:45 UTC, givaleria approved these changes

2022-04-21 16:25 UTC, fabiianZ approved these changes

2024-06-26 15:47 UTC, closed without merging